service: ${file(../serverless.common.yml):service}-db
frameworkVersion: ${file(../serverless.common.yml):frameworkVersion}

provider:
  name: 'aws'
  stage: ${file(../serverless.common.yml):provider.stage}
  region: ${file(../serverless.common.yml):provider.region}

resources:
  - Resources:
      GymDb:
        Type: AWS::DynamoDB::Table
        DeletionPolicy: Retain
        Properties: 
          TableName: ${self:service}-${self:provider.stage}-gym
          AttributeDefinitions: 
            - AttributeName: 'PK'
              AttributeType: S
            - AttributeName: 'SK'
              AttributeType: S
          KeySchema: 
            - AttributeName: PK
              KeyType: HASH
            - AttributeName: SK
              KeyType: RANGE
          GlobalSecondaryIndexes:
            - IndexName: InverseIndex
              KeySchema: 
                - AttributeName: SK
                  KeyType: HASH
                - AttributeName: PK
                  KeyType: RANGE
              Projection:
                ProjectionType: KEYS_ONLY
              ProvisionedThroughput: 
                ReadCapacityUnits: '12'
                WriteCapacityUnits: '12'
          BillingMode: PROVISIONED
          ProvisionedThroughput: 
            ReadCapacityUnits: '12'
            WriteCapacityUnits: '12'
  - Outputs:
      GymTableName:
        Description: The gym database table name used for DynamoDB queries via AWS-SDK
        Value: !Ref GymDb
        Export:
          Name: ${self:provider.stage}-GymTableName
      GymTableArn:
        Description: The gym database table ARN used to refer to the table in CloudFormation
        Value: !GetAtt GymDb.Arn
        Export:
          Name: ${self:provider.stage}-GymTableArn

